# Generated by Django 5.1.6 on 2025-04-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduwave_app', '0002_usuario_centro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_doc',
            field=models.CharField(choices=[('TI', 'Tarjeta de identidad'), ('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PEP', 'Permiso especial de permanencia'), ('PPT', 'Permiso por protecction especial'), ('OT', 'Otro')], default='CC', max_length=3),
        ),
    ]
