# Generated by Django 5.1.6 on 2025-04-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduwave_app', '0003_alter_usuario_tipo_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ficha',
        ),
        migrations.AddField(
            model_name='usuario',
            name='ficha',
            field=models.ManyToManyField(blank=True, to='Eduwave_app.ficha'),
        ),
    ]
