# Generated by Django 5.1.6 on 2025-04-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eduwave_app', '0004_remove_usuario_ficha_usuario_ficha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ficha',
            new_name='fichas',
        ),
    ]
