# Generated by Django 5.1.3 on 2025-04-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduwave_app', '0006_alter_inventario_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='inventario',
            field=models.ManyToManyField(blank=True, related_name='novedades_aprendiz', to='Eduwave_app.inventario'),
        ),
    ]
