# Generated by Django 5.1.3 on 2025-04-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eduwave_app', '0008_alter_novedad_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='inventario',
            field=models.ManyToManyField(blank=True, to='Eduwave_app.inventario'),
        ),
    ]
